### ISSUE TITLE
Can't access History for Simple Window Saver?

### ISSUE THREAD

**Issue by wizeguy** [nickbaum/simple-window-saver#20]
Hi there, love your Simple Window Saver Chrome Extension! 
Unfortunately a few days ago I did a Win 7 restore to a few days back and lost some of my extensions including Simple Window Saver that should have loaded as I've had it for at least a year..so not sure what the deal is?  Is there a folder I should look for to access the Simple Window history?  I'm afraid to install the Simple Window extension again so I don't overwrite my history.  

Can ANYONE please help?  I'd really like to be able to retrieve my windows as I had a bunch of windows saved.

**Comment by nickbaum** [comment]
Hi wizeguy,

I'm sorry for the trouble, it sucks to lose data. This has almost happened to me as well, so I understand how it feels.

The saved windows are stored in your Chrome profile. You can find information on where to find that here:

http://www.chromium.org/user-experience/user-data-directory

If you can retrieve that from your previous install, it should still have your saved windows. Unfortunately if you've lost your Chrome profile, I'm afraid there's no way to recover your saved windows.

I'd like to find a way to sync your windows to the cloud, or at least to periodically export them, but I haven't had a chance to implement those features yet.

**Comment by wizeguy** [comment]
Thanks for replying Nick, I was about to do another restore a few days ago, when your extension finally appeared!  I'm guessing after being logged in to gmail and syncing for a few weeks it finally remembered me?  However some other extensions are still missing, but I'm okay with re-installing those as they didn't save any important data. 

Other thing thats weird is when I try to view my chrome profile I can't find the "AppData" folder?  I can't find the "Local Settings", or "User Data" folder either?  Any idea please?

**Comment by nickbaum** [comment]
I'm not sure about the folders. What operating system are you using?

When the extension reappeared, did the saved windows show up as well?

**Comment by wizeguy** [comment]
Hi Nick, to answer your question, using Win7 and yes, the saved windows did reappear after I found it there the other day and enabled it, but it was missing for two weeks before?

I found the \User Data\Default folder..but don't see anything called Chrome Profile?  However I do see lots of other files for a profile such as Preferences, Cookies, Bookmarks etc.  Also I see two folders called Extensions and Extension State.  Inside the Extension folder is a bunch of folders with long random apha names.  I found the one for Simple Window Saver!   *So what file do I open or save as a backup?  

Also I noticed the Extension folder has a current modified date whereas the Extension State folder is a week behind with 8/30/12. I had 60 extensions (20 enabled) before the Win7 restore, now I only have 13 extensions (7 enabled).  So maybe Chrome is not updating the extensions state or syncing properly or?

**Comment by nickbaum** [comment]
Hi Wizeguy, I'm not quite sure why your extensions didn't sync earlier, but I'm sure happy that you recovered your windows. Phew! Sorry again for the scare and the late response on my part.

The "Default" folder actually contains your profile. The extensions folder contains the extensions themselves, whereas the saved windows are actually stored in something called LocalStorage. I'm not sure which file that is saved in, so the safest backup would be to periodically copy the entire "default" folder.

Hopefully I can add sync at some point in the future :)

PS: marking this as closed since you've recovered your windows.
