### ISSUE TITLE
CAN ANYBODY PLEASE HELP?!!  Thank you!

### ISSUE THREAD

**Issue by wizeguy** [nickbaum/simple-window-saver#21]
Hi there, love your Simple Window Saver Chrome Extension! 
Unfortunately a few days ago I did a Win 7 restore to a few days back and lost some of my extensions including Simple Window Saver that should have loaded as I've had it for at least a year..so not sure what the deal is? Is there a folder I should look for to access the Simple Window history? I'm afraid to install the Simple Window extension again so I don't overwrite my history.

Can ANYONE please help? I'd really like to be able to retrieve my windows as I had a bunch of windows saved.

**Comment by nickbaum** [comment]
Closing this issue since I replied to the previous one:

https://github.com/nickbaum/simple-window-saver/issues/20
