### ISSUE TITLE
show number of open tabs in badge

### ISSUE THREAD

**Issue by timoreimann** [nickbaum/simple-window-saver#22]
A few people on the Chrome App Store suggested to show the number of tabs currently open in a saved window on the badge instead of the little 'v' character. I'm quite fond of the idea so I'm putting it up as a feature request. 

What should he taken into account though is horizontal space limitations. I'm not sure if it's realistic but people may be using 100+ tabs at the same time. So for a certain threshold, the badge should just indicate that there are many tabs in a single window. This could be accomplished by showing something like '99+', for instance.

**Comment by nickbaum** [comment]
Great suggestion, implemented as of 1.4!
