### ISSUE TITLE
Update manifest to version 2

### ISSUE THREAD

**Issue by timoreimann** [nickbaum/simple-window-saver#23]
As noted in the [documentation](http://developer.chrome.com/extensions/manifestVersion.html), manifest version 1 was deprecated in Chrome 18. Starting with Chrome 23, extensions which haven't upgraded to version 2 will be blocked from updates, and during the course of the next year further, more strict restrictions will take effect. Simple Window Saver should therefore upgrade to manifest version 2.

Don't worry about doing the work yourself -- I've already carried out the manifest upgrade on my fork. A pull request will follow soon.

**Comment by nickbaum** [comment]
I just pushed version 1.4 which updates to manifest 2.0.
