### ISSUE TITLE
Disallow identical names

### ISSUE THREAD

**Issue by rgutter** [nickbaum/simple-window-saver#27]
You might want to prevent identical names from being accidentally used for sessions, especially as they can't be renamed. (Great product, btw)

**Comment by nickbaum** [comment]
Hi @rgutter, thanks for the suggestion. I think of duplicate window names as a feature, actually. For example, I have several windows named "read later", it's nice not to have to come up with different names for each one.

For renaming, the workaround is to open the window, delete the saved window, and resave it under a different name. It's a tad clunky, but it's one less thing to add to the UI.

**Comment by rgutter** [comment]
Hi Nick,

Afraid I have to disagree - I see a minor and very specific advantage at the cost of great potential confusion. As an old UI designer, I'd suggest you're violating a pretty basic concepts by allowing objects - in the absence of context - to share a unique and meaningful identifier . That's especially true given user expectations. You wouldn't want to name a bunch of files "read later" in a file system unless they were in a clearly visible parallel or hierarchical structure. Or have the same label on multiple links on a web page unless they were clearly differentiated by the surrounding text.

My two cents worth. And regardless, I really appreciate your product. Thanks.

**Comment by nickbaum** [comment]
I see your point, though I would argue that there is some context (number
of tabs, date last opened i.e. sort order).

If it's important to distinguish two windows, users can name them
differently. If it's not important, then there's little risk of confusion,
and I haven't introduced an additional restriction.
