### ISSUE TITLE
Add sync ability

### ISSUE THREAD

**Issue by trusktr** [nickbaum/simple-window-saver#9]
Add a way to sync the windows across different computers, maybe by using google account login or something, etc.

Check out the "TabCloud" plugin to see how it does it's syncing. It's code is available here on github too:
https://github.com/Connorhd/TabCloud

You too both have the best plugins, yours because it automatically keeps the state of the saved window updated, and TabCloud because it syncs nicely across all computers.

**Comment by nickbaum** [comment]
Thanks for posting this. I'm marking it as closed as we have already captured it here:

https://github.com/nickbaum/simple-window-saver/issues/7
